version: "3"
services:
  avaldao-dapp:
    container_name: avaldao-dapp
    build: ./dapp
    image: acdi/avaldao-dapp
    ports:
      - "3010:3010"
    stdin_open: true
    volumes:
      - .env:/usr/src/app/.env
      - ./dapp/config/configuration.js:/usr/src/app/src/configuration.js
      - ${DAPP_PATH_SRC}:/usr/src/app/src
      - ${DAPP_PATH_PUBLIC}:/usr/src/app/public
      - ${AVALDAO_CONTRACT_PATH_SRC}:/usr/src/app/node_modules/@acdi/avaldao-contract
      - ${EFEM_CONTRACT_PATH_SRC}:/usr/src/app/node_modules/@acdi/efem-contract
#     - ${EFEM_DAPP_PATH_SRC}:/home/efem-dapp/dist
      - ${EFEM_DAPP_PATH_SRC}:/usr/src/app/node_modules/@acdi/efem-dapp/dist
    depends_on:
      - avaldao-ipfs
      - avaldao-mongodb
      - avaldao-feathers

  avaldao-feathers:
    container_name: avaldao-feathers
    build: ./feathers
    image: acdi/avaldao-feathers
    ports:
      - "3030:3030"
    volumes:
      - .env:/usr/src/app/.env
      - ./feathers/config/default.json:/usr/src/app/config/default.json
      - ./feathers/config/authentication.js:/usr/src/app/config/authentication.js
      - ${FEATHERS_PATH_SRC:-./feathers/src}:/usr/src/app/src
    depends_on:
      - avaldao-ipfs
      - avaldao-mongodb
      
  avaldao-efem-users-feathers:
    container_name: avaldao-efem-users-feathers
#    build: ./efem-users-feathers
    image: acdi/efem-users-feathers
    ports:
      - "3031:3030"
    volumes:
      - .env:/usr/src/app/.env
      - ./efem-users-feathers/config/config.js:/usr/src/app/config/config.js
      - ./efem-users-feathers/config/default.json:/usr/src/app/config/default.json
      - ./efem-users-feathers/config/authentication.js:/usr/src/app/config/authentication.js
      - ${FEATHERS_USER_PATH_SRC}:/usr/src/app/src
      - ${EFEM_CONTRACT_PATH_SRC}:/usr/src/app/node_modules/@acdi/efem-contract

  avaldao-mongodb:
    container_name: avaldao-mongodb
    image: mongo:5.0.0
    ports:
      - "27017:27017"

  avaldao-ipfs:
    container_name: avaldao-ipfs
    image: acdi/avaldao-ipfs
    build: 
      context: ./ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ${IPFS_DATA:-./ipfs/data}:/data/ipfs
      - ${IPFS_EXPORT:-./ipfs/export}:/export

  