version: "3"
services:
  avaldao-dapp:
    container_name: avaldao-dapp
    image: acdi/avaldao-dapp
    stdin_open: true
    depends_on:
      - avaldao-ipfs
      - avaldao-mongodb
      - avaldao-feathers

  avaldao-feathers:
    container_name: avaldao-feathers
    image: acdi/avaldao-feathers
    depends_on:
      - avaldao-ipfs
      - avaldao-mongodb

  avaldao-ipfs:
    container_name: avaldao-ipfs
    image: acdi/avaldao-ipfs
    build: 
      context: ./ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ${IPFS_DATA:-./ipfs/data}:/data/ipfs
      - ${IPFS_EXPORT:-./ipfs/export}:/export

  avaldao-mongodb:
    container_name: avaldao-mongodb
    image: mongo:5.0.0
    ports:
      - "27017:27017"