version: "3"
services:
  avaldao-feathers:
    container_name: avaldao-feathers
    image: acdi/avaldao-feathers:latest
    ports:
      - "7030:3030"
    restart: always
    volumes:
      - /etc/avaldao/feathers/default.json:/usr/src/app/config/default.json
      - /etc/avaldao/feathers/.env:/usr/src/app/.env 
#    depends_on:
#      - efem-ipfs

# Descomentar las siguientes lineas en caso de que sea necesario levantar ipfs como servicio
# Tambien se puede utilizar el de give4forest https://give4forest.org/ipfs/
#
#  efem-ipfs:
#    container_name: avaldao-ipfs
#    image: acdi/give4forests-ipfs
#    ports:
#      - "4001:4001"     # Swarm tcp, should be exposed to the public
#      - "4001:4001/udp" # Swarm tcp, should be exposed to the public
#      - "5001:5001"     # Daemon API; must not be exposed publicly but to client services under you control
#      - "8080:8080"     # Web Gateway
#    restart: always
#
#    volumes:
#      - ipfs-data:/data/ipfs
#      - ipfs-export:/export
#
#volumes:
#  ipfs-data:
#  ipfs-export:
