version: "3"
services:
  avaldao-feathers:
    container_name: avaldao-feathers
    image: acdi/avaldao-feathers:latest
    ports:
      - "3030:3030"
    restart: always
    volumes:
      - /etc/avaldao/feathers/default.json:/usr/src/app/config/default.json
      - /etc/avaldao/feathers/.env:/usr/src/app/.env